# -*- mode: ruby -*-
# vi: set ft=ruby :

NUM_WORKER_NODES = 2

Vagrant.configure("2") do |config|

  config.vm.box = "generic/ubuntu2204"
  config.vm.box_check_update = false

  # CONTROL PLANE
  config.vm.define "controlplane" do |node|

    node.vm.hostname = "controlplane"

    node.vm.network "private_network", type: "dhcp"

    node.vm.provider :libvirt do |libvirt|
      libvirt.storage_pool_name = "vagrant"
      libvirt.memory = 4096
      libvirt.cpus = 2
    end

    node.vm.provision "shell",
      path: "setup-hosts.sh",
      args: [NUM_WORKER_NODES]

    node.vm.provision "shell",
      path: "update-dns.sh"

    node.vm.provision "shell",
      path: "ssh.sh"

    node.vm.provision "file",
      path: "disable-swap.sh",

    node.vm.provision "file",
      source: "./vimrc",
      destination: "/home/vagrant/.vimrc"

  end

  # WORKER NODES
  (1..NUM_WORKER_NODES).each do |i|

    config.vm.define "node0#{i}" do |node|

      node.vm.hostname = "node0#{i}"

      node.vm.network "private_network", type: "dhcp"

      node.vm.provider :libvirt do |libvirt|
        libvirt.storage_pool_name = "vagrant"
        libvirt.memory = 3072
        libvirt.cpus = 2
      end

      node.vm.provision "shell",
        path: "setup-hosts.sh",
        args: [NUM_WORKER_NODES]

      node.vm.provision "shell",
        path: "update-dns.sh"

      node.vm.provision "shell",
        path: "ssh.sh"

      node.vm.provision "file",
        path: "disable-swap.sh",
   
    end

  end
end
